Instructions Page
utmgdsc/UML_Mentor pull request #33
Opened 2024-02-26 23:16 UTC by o-bm

Created the instructions page. It fetches instructions data (In JSON format) from the back end and render it dynamically to display to the user. 
It is very easy to add or modify the instructions as you can just make changes to the structure in InstructionsController.js. Each instruction has a title and a body that is used to display on frontend. 

Note that there is a previous branch called instructions_page but something got messed up because of an update to main that I needed  so I will delete it. Nothing to worry about there. 

Also I suggest that we maybe use the instructions page as a FAQ. I think this will be better for the application and we can address common issues or questions that users may have while still including the instructions on how to use the app.

close #32

2024-02-27 05:22 UTC, arthurhohinng reviewed
Could I get an example of when the instructions page is used?
Also an image would be helpful

2024-02-27 05:22 UTC, arthurhohinng commented on client/src/pages/InstructionsPage.tsx
> +const InstructionsPage: React.FC = () => {
React.FC isn't preferred
https://github.com/facebook/create-react-app/pull/8177

2024-02-28 06:08 UTC, Vladmidir requested changes
I strongly suggest you remove the server components.

Also, the ticket implied that you will write the actual instructions content.

2024-02-28 06:08 UTC, Vladmidir commented on client/src/pages/InstructionsPage.tsx
> +    fetch('/api/instructions')
we can hardcode instructions on the client side.

2024-02-28 19:37 UTC, o-bm commented on server/routes/InstructionsRoutes.js
Agreed. Will have the instructions hardcoded and make it a react component

2024-02-28 19:37 UTC, o-bm commented on server/index.js
> +app.use('/api', instructionsRoutes);
Thanks for pointing that out

2024-02-28 19:39 UTC, o-bm commented on client/src/pages/InstructionsPage.tsx
> +interface Instruction {
noted

2024-02-28 19:41 UTC, o-bm commented on server/controllers/InstructionsController.js
> +    {title: "Getting Started", body: "This is a new instruction"},
will do

2024-03-05 19:37 UTC, o-bm commented
Removed backend integration for  instructions 
Made react component for instructions
Updated challenge page so instructions pop up when a user clicks on a challenge 

<img width="1270" alt="image" src="https://github.com/utmgdsc/UML_Mentor/assets/84227399/564601f5-1f8a-4baa-a285-ec850e0230f2">

2024-03-07 18:55 UTC, merged